#!/bin/bash

####################################################################
#
# Make a PDF from any text file
#
# Creates a pdf from any text file.
#
# Repo: https://github.com/nclarx/handy-markdown-functions
#
# Dependencies
#
# Pandoc: https://pandoc.org/installing.html
# Wkhtmltopdf: https://wkhtmltopdf.org/downloads.html
#
# Usage:
#
# Call this function with a text file input and path to a output file and
# it will generate a pdf of the text file.
#
# Args:
#
# $1: the path to and name of the input file
#
# $2: the path to and name of the output file
#
# Example: `mkPdf test.md test.pdf`
#
#############################################################################

inputFile=$1
outputFile=$2
pandoc $inputFile -t HTML5 |
    wkhtmltopdf - $outputFile
